// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFVa4RIkRZX_sPKhhPNhuToQnWLGQ-lYc',
    appId: '1:392307752111:web:fcd58893146e6432f2e85a',
    messagingSenderId: '392307752111',
    projectId: 'taskerapp-197ed',
    authDomain: 'taskerapp-197ed.firebaseapp.com',
    storageBucket: 'taskerapp-197ed.firebasestorage.app',
    measurementId: 'G-04W862JML0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAjtruobWb0iVJELxzDf3V006Uj9a6sLo',
    appId: '1:392307752111:android:5aaaead4fd533125f2e85a',
    messagingSenderId: '392307752111',
    projectId: 'taskerapp-197ed',
    storageBucket: 'taskerapp-197ed.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWqAXWB9ytnwq28eAwoUU9QslkYTY3RNk',
    appId: '1:392307752111:ios:0418082d42242cfef2e85a',
    messagingSenderId: '392307752111',
    projectId: 'taskerapp-197ed',
    storageBucket: 'taskerapp-197ed.firebasestorage.app',
    iosBundleId: 'com.example.taskerAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWqAXWB9ytnwq28eAwoUU9QslkYTY3RNk',
    appId: '1:392307752111:ios:0418082d42242cfef2e85a',
    messagingSenderId: '392307752111',
    projectId: 'taskerapp-197ed',
    storageBucket: 'taskerapp-197ed.firebasestorage.app',
    iosBundleId: 'com.example.taskerAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCFVa4RIkRZX_sPKhhPNhuToQnWLGQ-lYc',
    appId: '1:392307752111:web:31e9f3c70f06aff5f2e85a',
    messagingSenderId: '392307752111',
    projectId: 'taskerapp-197ed',
    authDomain: 'taskerapp-197ed.firebaseapp.com',
    storageBucket: 'taskerapp-197ed.firebasestorage.app',
    measurementId: 'G-FCS1YGKB7T',
  );
}
